### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by ahmedalejo**
Fixed small doc typo

### CODE REVIEW

**Comment by ghuntley** [comment]
cheers for the PR @ahmedalejo but the doc is right?

IF 'diagnostics is enabled' then wrap with `HttpClientDiagnosticsHandler innerHandler` else use `innerHandler`

**Comment by ahmedalejo** [comment]
Ok so were did `messageHandler` com from? totally unusing innerHandler

**Comment by ghuntley** [comment]
You're right. Apologies - have resolved.

**Comment by ahmedalejo** [comment]
cool

**Pull request closed without merging**
